<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SMRM - Social Media Relationship Manager')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
                        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/application.css')
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Source+Sans+Pro')
                        ->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css')
                        ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <div id="wrapper" class="container-fluid">
            <div id="sidebar-wrapper">
                <ul id="sidebar-menu" class="sidebar-nav">
                    <li class="sidebar-brand"><a id="menu-toggle" href="/">SMRM<span id="main_icon" class="fa fa-ellipsis-v fa-lg"></span></a></li>
                </ul>
                <ul class="sidebar-nav">
                    <li><a href="/">All Feeds<span class="fa-sub_icon fa fa-bullhorn fa-lg"></span></a></li>
                </ul>
                <ul class="sidebar-nav sidebar-bottom">
                    <li><a href="/admin">Admin<span class="fa-sub_icon fa fa-cog fa-lg"></span></a></li>
                    <li><a href="/user/logout">Logout<span class="fa-sub_icon fa fa-sign-out fa-lg"></span></a></li>
                </ul>
            </div>
            <div id="page-content-wrapper">
                <div class="page-content inset">
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript()
                        ->prependFile($this->basePath() . '/js/application.js')
                        ->prependFile('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js')
                        ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js') ?>
    </body>
</html>
