<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SMRM - Social Media Relationship Manager')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
                        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/application.css')
                        ->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css')
                        ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript(); ?>
    </head>
    <body>

        <div class="container">
            
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript()
                        ->prependFile($this->basePath() . '/js/application.js')
                        ->prependFile('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js')
                        ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js') ?>
    </body>
</html>
