<?php
	// Adding in Infinite Scroll here for use in the main application page.
	$this->inlineScript()->appendFile('//cdnjs.cloudflare.com/ajax/libs/jquery-infinitescroll/2.0b2.120519/jquery.infinitescroll.min.js')
						 ->appendFile($this->basePath() . '/js/index.js');

	$this->headLink()->appendStylesheet($this->basePath() . '/css/index.css');
?>
<div id="wrapper">
	<div id="sidebar-wrapper">
		<ul id="sidebar-menu-toggle" class="sidebar-nav">
			<li class="sidebar-brand">
				<a id="menu-toggle">Networks <i class="fa fa-fw fa-lg fa-bars" id="main-icon"></i></a>
			</li>
		</ul>
		<ul class="sidebar-nav">
			<?php echo $this->networkSidebar() ?>
		</ul>
	</div>
</div>